version: "3"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
      - IS_LOGGED=false
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  website:
    build: ./website
    ports:
        - "8081:8081"
    volumes:
      - ./website/:/common_volume
  mobile:
    build: ./mobile
    volumes:
      - ./mobile/:/common_volume

volumes:
  db-data:
    driver: local
